source 'https://rubygems.org'

ruby '2.0.0'

gem 'rack', '~> 1.6.0'
gem 'rack-cors', :require => 'rack/cors'
gem 'grape'
gem 'grape-kaminari'
gem 'grape-entity'
gem 'grape-swagger'
gem 'activerecord', '~> 4.2.0', require: 'active_record'
gem 'grape-activerecord'
gem 'pg'
gem 'postgres_ext'
gem 'rake'
